package main

import "fmt"

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

/*
一道正常的 Fibonacci
*/
func prob2() int {

	a, b, result := 1, 2, 0

	for b <= 4000000 {

		if b%2 == 0 {
			result += b
		}

		b = a + b
		a = b - a
	}

	return result
}

func main() {
	fmt.Println(prob2())
}
